In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('fake-news/train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df=df.dropna()

In [5]:
x=df.drop('label',axis=1)

In [6]:
x

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [7]:
y=df['label']

In [8]:
x.shape

(18285, 4)

In [9]:
y.shape

(18285,)

In [10]:
import tensorflow as tf

In [11]:
tf.__version__

'2.10.0'

In [12]:
from tensorflow .keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import keras
from keras.layers import Dense, LSTM,Dropout
from keras import Sequential
from keras.preprocessing.text import one_hot

In [13]:
###vocabulary size
voc_size=5000

OneHot Representation

In [14]:
messages= x.copy()

In [15]:
messages.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
onehot_repr=[one_hot(words,voc_size) for words in corpus]
onehot_repr

[[2457, 2294, 3179, 4973, 1134, 726, 1164, 600, 2365, 1971],
 [119, 2875, 2947, 602, 1276, 2875, 4083],
 [194, 1974, 271, 355],
 [1309, 3463, 2626, 4875, 2055, 2934],
 [4352, 1276, 604, 3365, 3433, 2981, 1276, 3021, 3934, 2397],
 [2616,
  1668,
  1502,
  3774,
  2426,
  4715,
  2373,
  409,
  1649,
  3295,
  189,
  3816,
  733,
  1894,
  4083],
 [1371, 1351, 1007, 2575, 3601, 2148, 3431, 3739, 2370, 1433, 723],
 [225, 1092, 3885, 2347, 1361, 575, 4715, 663, 2370, 1433, 723],
 [954, 473, 690, 2932, 4899, 3258, 4037, 2731, 4715, 2677],
 [3418, 1073, 4737, 2158, 2285, 4443, 3086, 358],
 [4462, 4536, 755, 4233, 2004, 642, 182, 3671, 3515, 4875, 1041],
 [4875, 2463, 1134, 3258, 4715, 1361],
 [1832, 4784, 1889, 3568, 4106, 4245, 4237, 2061, 2095],
 [2461, 3985, 3101, 4124, 4240, 651, 3940, 2370, 1433, 723],
 [1947, 4893, 1666, 218, 4199, 2370, 1433, 723],
 [3440, 1897, 1127, 1350, 4507, 3759, 4141, 1525, 3235, 3601],
 [916, 686, 2875],
 [2337, 4858, 3003, 2835, 4715, 199, 4475, 4083],
 [559,

In [20]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  600 2365 1971]
 [   0    0    0 ... 1276 2875 4083]
 [   0    0    0 ... 1974  271  355]
 ...
 [   0    0    0 ... 2370 1433  723]
 [   0    0    0 ... 1653 1628  914]
 [   0    0    0 ...  924  521 1886]]


In [21]:
len(embedded_docs)

18285

**Creating Model**

In [39]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_8 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_7 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [23]:
len(embedded_docs),y.shape

(18285, (18285,))

In [24]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [25]:
x_final.shape,y_final.shape

((18285, 20), (18285,))

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.33,random_state=42)

In [28]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 16s 29ms/step - loss: 0.3441 - accuracy: 0.8405 - val_loss: 0.1965 - val_accuracy: 0.9148
Epoch 2/10
192/192 [==============================] - 4s 19ms/step - loss: 0.1515 - accuracy: 0.9418 - val_loss: 0.1907 - val_accuracy: 0.9186
Epoch 3/10
192/192 [==============================] - 3s 18ms/step - loss: 0.1107 - accuracy: 0.9576 - val_loss: 0.2171 - val_accuracy: 0.9198
Epoch 4/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0827 - accuracy: 0.9693 - val_loss: 0.2275 - val_accuracy: 0.9140
Epoch 5/10
192/192 [==============================] - 3s 18ms/step - loss: 0.0616 - accuracy: 0.9775 - val_loss: 0.2856 - val_accuracy: 0.9158
Epoch 6/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0511 - accuracy: 0.9815 - val_loss: 0.3227 - val_accuracy: 0.9109
Epoch 7/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0345 - accuracy: 0.9891 - val_loss: 0.3311 - val_accuracy: 0.905

In [29]:
y_pred = model.predict(x_test)

189/189 [==============================] - 2s 4ms/step


In [30]:
y_pred

array([[9.9990082e-01],
       [7.9827922e-05],
       [2.1154699e-03],
       ...,
       [7.7336091e-07],
       [9.7627425e-01],
       [9.9960405e-01]], dtype=float32)

In [31]:
y_pred_classes = (y_pred > 0.5).astype(int)


In [32]:
y_pred_classes

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [34]:
confusion_matrix(y_test,y_pred_classes)

array([[3138,  281],
       [ 255, 2361]], dtype=int64)

In [35]:
accuracy_score(y_test,y_pred_classes)

0.9111847555923778